---

- include_tasks: start.yml
  when: >
    control_action == 'StartSystem' or
    control_action == 'Start'


- include_tasks: stop.yml
  when: >
    control_action == 'StopSystem' or
    control_action == 'Stop'
