    - name: SAP Instance '{{ control_action }}'
      shell: "/usr/sap/hostctrl/exe/sapcontrol -nr {{ control_instance_nr }} -function {{ control_action }}"
      become: true
      become_user: "{{ control_sid }}adm"

    - name: Wait for stopped 
      shell: "/usr/sap/hostctrl/exe/sapcontrol -nr {{ control_instance_nr }} -function WaitforStarted {{ control_waittimeout }} 2"
      register: outs
      become: true
      become_user: "{{ control_sid }}adm" 

    - debug: var=outs.stdout
    