
- name: Creating input files for templates
  template:
    src: "{{ item }}.ctl.j2"
    dest: "{{ scripts_dir }}/{{ target_sap_sid }}_{{ item }}.ctl"
    owner: "{{ target_sap_sid }}adm"
  loop:
    - export_rsectab
    - export_tables
    
- name: Export tables
  shell: "source ~/.sapenv.csh && R3trans -v -w {{ scripts_dir }}/{{ filename }}.log {{ scripts_dir }}/{{ filename }}.ctl"
  become: true
  become_user: "{{ target_sap_sid }}adm"
  register: command_result
  failed_when: command_result.rc >= 8
  vars:
    filename: "{{ target_sap_sid }}_{{item}}"
  args:
    executable: /bin/csh
    creates: "{{ scripts_dir }}/{{ filename }}.dat"
  loop:
    - export_rsectab
    - export_tables


- debug: var=item.stdout
  loop: "{{ command_result.results }}"
  loop_control:
    label: "{{ item.item }}"  