- include_tasks: update_hdbuserstore_key.yml

- include_tasks: import_tables.yml

- include_tasks: correct_scc4_settings.yml

- include_tasks: correct_originals.yml

- include_tasks: truncate_tables.yml
